
import bisectionmethod.SimpleCalculator;
import java.awt.Color;
import java.awt.Font;
import java.util.function.Function;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

    public class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Mainframe() {
        initComponents();
        
        tableModel.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tableModel.getTableHeader().setOpaque(false);
        tableModel.getTableHeader().setBackground(new Color(204,255,204));
        tableModel.getTableHeader().setForeground(new Color(0,0,0));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        functionField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lowerBoundField = new javax.swing.JTextField();
        upperBoundField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maxIterationsField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Johnel Ian Songco\\Downloads\\rot.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Root Finder");
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFont(new java.awt.Font("Impact", 0, 10)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1222, 600));
        setMinimumSize(new java.awt.Dimension(1222, 600));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Johnel Ian Songco\\Downloads\\bgg-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 0, 190, 150);

        functionField.setBackground(new java.awt.Color(204, 255, 204));
        functionField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        functionField.setForeground(new java.awt.Color(0, 204, 102));
        functionField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        functionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionFieldActionPerformed(evt);
            }
        });
        getContentPane().add(functionField);
        functionField.setBounds(235, 166, 156, 60);

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("BRACKETING");
        jLabel5.setIconTextGap(6);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 6, 130, 30);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Enter the function in terms of x: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 170, 180, 60);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Enter the initial guess for lower bound:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 240, 200, 60);

        lowerBoundField.setBackground(new java.awt.Color(204, 255, 204));
        lowerBoundField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        lowerBoundField.setForeground(new java.awt.Color(0, 204, 51));
        getContentPane().add(lowerBoundField);
        lowerBoundField.setBounds(235, 238, 156, 60);

        upperBoundField.setBackground(new java.awt.Color(204, 255, 204));
        upperBoundField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        upperBoundField.setForeground(new java.awt.Color(0, 204, 102));
        upperBoundField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upperBoundFieldActionPerformed(evt);
            }
        });
        getContentPane().add(upperBoundField);
        upperBoundField.setBounds(235, 316, 156, 60);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("Enter the second guess for upper bound:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 310, 210, 60);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 153));
        jLabel4.setText("Input the maximum iteration:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 390, 150, 68);

        maxIterationsField.setBackground(new java.awt.Color(204, 255, 204));
        maxIterationsField.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        maxIterationsField.setForeground(new java.awt.Color(0, 204, 102));
        getContentPane().add(maxIterationsField);
        maxIterationsField.setBounds(235, 396, 156, 60);

        tableModel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 153), 3, true));
        tableModel.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        tableModel.setForeground(new java.awt.Color(0, 153, 51));
        tableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteration", "Lower Bound", "Upper Bound", "Mid Point", "Lower Bound f(x)", "Upper Bound f(x)", "Function Value", "Percent Error"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableModel.setColumnSelectionAllowed(true);
        tableModel.setEnabled(false);
        tableModel.setGridColor(new java.awt.Color(0, 204, 0));
        tableModel.setName(""); // NOI18N
        tableModel.setOpaque(false);
        tableModel.setRowSelectionAllowed(false);
        tableModel.setSelectionBackground(new java.awt.Color(0, 204, 102));
        tableModel.setSelectionForeground(new java.awt.Color(0, 153, 0));
        tableModel.setShowGrid(false);
        tableModel.setShowVerticalLines(true);
        tableModel.setSurrendersFocusOnKeystroke(true);
        tableModel.getTableHeader().setReorderingAllowed(false);
        tableModel.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tableModel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 10, 800, 539);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("CALCULATE (BISECTION METHOD)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 460, 200, 40);

        jButton2.setBackground(new java.awt.Color(255, 0, 102));
        jButton2.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 204));
        jButton2.setText("CLEAR TABLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 480, 160, 50);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText(" CALCULATE FALSE POSITION");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 510, 200, 40);

        jLabel6.setBackground(new java.awt.Color(255, 204, 204));
        jLabel6.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 51));
        jLabel6.setText("METHOD");
        jLabel6.setIconTextGap(6);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(226, 48, 165, 40);

        jLabel7.setBackground(new java.awt.Color(255, 204, 204));
        jLabel7.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("CALCULATOR");
        jLabel7.setIconTextGap(6);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(138, 100, 253, 54);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1110, 560, 0, 0);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Johnel Ian Songco\\Downloads\\bg.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, -20, 840, 950);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Johnel Ian Songco\\Downloads\\bg2.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 410, 690);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private boolean validateInput() {
        String functionStr = functionField.getText().trim();
        String lowerBoundStr = lowerBoundField.getText().trim();
        String upperBoundStr = upperBoundField.getText().trim();
        String maxIterationsStr = maxIterationsField.getText().trim();

        return !functionStr.isEmpty() && !lowerBoundStr.isEmpty() && !upperBoundStr.isEmpty() && !maxIterationsStr.isEmpty();
    }
     
     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (validateInput()) {
                    executeBisectionMethod();
                } else {
                    JOptionPane.showMessageDialog(Mainframe.this,
                            "Please fill in all fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
                }
            }
    
    
    
    private void executeBisectionMethod() {
        
        String functionStr = functionField.getText();
        double lowerBound = Double.parseDouble(lowerBoundField.getText());
        double upperBound = Double.parseDouble(upperBoundField.getText());
        int maxIterations = Integer.parseInt(maxIterationsField.getText());

        java.util.function.Function<Double, Double> function = x -> {
            String replaced = functionStr.replace("x", String.valueOf(x));
            return evaluate(replaced);
        };
        BisectionMethodCalculator calculator = new BisectionMethodCalculator(this);
        calculator.calculate(function, lowerBound, upperBound, maxIterations);
        }

    

    private double evaluate(String expression) {
        return SimpleCalculator.evaluate(expression);
    
    }
    
   
    public static void addToTable(int iteration, double lowerBound, double upperBound, double midPoint, Function<Double, Double> function, double functionValue, double percentError) {
        double lowerBoundFunctionValue = function.apply(lowerBound);
        double upperBoundFunctionValue = function.apply(upperBound);
        DefaultTableModel model = (DefaultTableModel) tableModel.getModel();
        model.addRow(new Object[]{iteration, lowerBound, upperBound, midPoint, lowerBoundFunctionValue, upperBoundFunctionValue, functionValue, percentError});
}
    
     private void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tableModel.getModel();
        model.setRowCount(0); // Remove all rows from the table   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clearTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void functionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_functionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_functionFieldActionPerformed

    private void calculateFalsePosition() {
        String functionStr = functionField.getText();
        double lowerBound = Double.parseDouble(lowerBoundField.getText());
        double upperBound = Double.parseDouble(upperBoundField.getText());
        int maxIterations = Integer.parseInt(maxIterationsField.getText());

        Function<Double, Double> function = x -> {
            String replaced = functionStr.replace("x", String.valueOf(x));
            return evaluate(replaced);
        };

  
       FalsePositionMethodCalculator calculator = new FalsePositionMethodCalculator(this);
        calculator.calculate(function, lowerBound, upperBound, maxIterations);
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (validateInput()) {
                    calculateFalsePosition();
                } else {
                    JOptionPane.showMessageDialog(Mainframe.this,
                            "Please fill in all fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
    
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void upperBoundFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upperBoundFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upperBoundFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField functionField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lowerBoundField;
    private javax.swing.JTextField maxIterationsField;
    private static javax.swing.JTable tableModel;
    private javax.swing.JTextField upperBoundField;
    // End of variables declaration//GEN-END:variables
}